# Generated by Django 3.1.5 on 2021-01-31 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 14, 32, 18, 181825, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='userpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 14, 32, 18, 181825, tzinfo=utc), null=True),
        ),
    ]
