# Generated by Django 3.1.5 on 2021-01-31 14:35

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210131_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 14, 35, 14, 727104, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
